version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    volumes:
      - ./data/mosquitto:/mosquitto/data
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: i2c-bridge
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    depends_on:
      - mosquitto
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: web-ui
    ports:
      - "8080:80"
    depends_on:
      - mosquitto
    restart: unless-stopped
